### ISSUE TITLE
Webservice integration

### ISSUE THREAD

**Issue by ChrisdAutume** [buckless-team/server#147]
Permettrait la liaison avec des services extérieurs. Plusieurs cas possible:
- hook: déclenchement d'une notification a l'achat d'un item (ex: cotisation, billetterie etc etc)
- facturation extérieur: paiement en ligne, facturation a la durée (ex: techlab ...). 

(On en avait parlé il y'a qq temps)

**Comment by gjuchault** [comment]
FIxed by #243
